<?php declare(strict_types=1);

namespace Native\Mobile\Contracts\Permissions;

/**
 * Contract for permission result events.
 *
 * Implement this interface for events emitted as a result of permission requests.
 * For status checks (not requests), use PermissionStatusContract instead.
 *
 * @see PermissionStatusContract
 */
interface PermissionResultContract
{
    /**
     * Get the plugin identifier (who requested the permission).
     *
     * @return string Plugin identifier (e.g., "camera", "firebase", "geolocation")
     */
    public function source(): string;

    /**
     * Get the unique request correlation token.
     *
     * This is an opaque blob generated by the permission coordinator.
     * It MUST be unique per request and MUST NOT be reused across concurrent requests.
     *
     * @return string Opaque request token (e.g., "req_01HZ...")
     */
    public function sourceId(): string;

    /**
     * Get the platform permission identifier.
     *
     * @return string Platform permission string (e.g., "android.permission.CAMERA")
     */
    public function permission(): string;

    /**
     * Get the permission status.
     *
     * @return PermissionStatus Enum value indicating the result
     */
    public function status(): PermissionStatus;
}
